version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_store
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: store
    ports:
      - "5433:5432" # Puerto 5432 para PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data 
volumes:
  postgres_data:
